#!/usr/bin/env bash

dir="$HOME/.config/rofi"
theme="adrien/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

rofi_command="rofi -dmenu -theme $dir/$theme"

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""
yes=''
no=''

confirm() {
    echo -e "$yes\n$no" | $rofi_command -me-select-entry "" -me-accept-entry "MousePrimary" -p 'Are you sure ?' -selected-row 1
}

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -me-select-entry "" -me-accept-entry "MousePrimary" -p "Uptime: $uptime" -selected-row 2)"
case $chosen in
    $shutdown)
        ans=$(confirm &)
        if [[ $ans == $yes ]]; then
            systemctl poweroff
        elif [[ $ans == $no ]]; then
            exit 0
        fi
        ;;
    $reboot)
        ans=$(confirm &)
        if [[ $ans == $yes ]]; then
            systemctl reboot
        elif [[ $ans == $no ]]; then
            exit 0
        fi
        ;;
    $lock)
        sl
        ;;
    $suspend)
        scr_sleep
        ;;
    $logout)
        ans=$(confirm &)
        if [[ $ans == $yes ]]; then
            i3-msg exit
        elif [[ $ans == $no ]]; then
            exit 0
        fi
        ;;
esac

