#!/usr/bin/env bash

echo=0

while getopts "e" option
do
    case $option in
        e)
            echo=1
            ;;
    esac
done

shift $(($OPTIND - 1))

lockfile="/tmp/$(basename $0).lock"

if [[ -f "${lockfile}" ]]; then
    notify-send -i /home/id0827502/images/icons/password.png -t 5000 -u normal "Quickpass instance already open!"
    i3 "[instance="quickpass"] focus"
    exit 1
else
    echo $$ > "${lockfile}"
fi

trap "rm ${lockfile}" 0

#pointer="#FFAB84"
#prompt="#01AB84"
#header="#01AB84"
#hl="#01AB84"

#fzf_colours="--color=fg:#888888,bg:-1,fg+:#FFFFFF,pointer:$pointer,prompt:$prompt,header:$header,hl:$hl,hl+:#FFFFFF"
selected_pass=$(pass git ls-files '*.gpg' | sed 's/.gpg$//' | fzf --margin=5%,5% --header="Select a password:")
clipboard_expiry=15000

if [ -z "${selected_pass}" ]; then
    exit
else
    case "${selected_pass}" in
        *"otp"*)
            pass otp "${selected_pass}" | tr -d '\n' | xsel -bi -t "${clipboard_expiry}"
            ;;
        *)
            if [ $echo -eq 1 ]; then
                pass show "${selected_pass}"
            else
                pass "${selected_pass}" | tr -d '\n' | xsel -bi -t "${clipboard_expiry}"
            fi
    esac
fi
