#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "-t" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -i -matching fuzzy -dmenu "$@" -p "Pass : ")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" &>/dev/null
else
    passtext=$(pass show $password)
    notify -b $passtext Password
fi

